### ISSUE TITLE
recursor doesn't start

### ISSUE THREAD

**Issue by daudo** [chrisss404/powerdns#17]
using the "private authoritative" [docker-compose.yml](https://github.com/chrisss404/powerdns/blob/master/samples/private-authoritative/docker-compose.yml) file without any changes, the recursor fails to start.

It bails out saying 

"cp: can't stat '/etc/powerdns/recursor.conf-dist': No such file or directory"

If I see it right, the [Dockerfile](https://github.com/chrisss404/powerdns/blob/master/recursor/Dockerfile) for the recursor lacks the following line:

COPY ./conf /etc/powerdns

Because of this, docker-entrypoint.sh cannot create /etc/powerdns/recursor.conf from the (non existing) recursor.conf-dist file. But maybe I am missing something?

**Comment by chrisss404** [comment]
Hi daudo,
it seems like there is something wrong with the latest version. I'll have a look, thanks for reporting.
Meanwhile you can use one of the release versions, e.g.: `5.0.2-recursor`

BR
Christian

**Comment by daudo** [comment]
yes, that did the trick, thanks for the swift reply!

**Comment by chrisss404** [comment]
Fixed. Added proper yaml support to latest recursor.
