### ISSUE TITLE
powerdns doesn't resolve with the AA flag

### ISSUE THREAD

**Issue by firstdorsal** [chrisss404/powerdns#3]
hi your project is working great for me its resolving my records without problems now. thank you!

my only problem now is that it doesn't resolve authoritative queries with the AA flag. its just missing.
i can't find out why and how i would set it.

in the faq this can be found but it should still send the AA bit shouldn't it? 
https://doc.powerdns.com/authoritative/appendices/FAQ.html#powerdns-does-not-give-authoritative-answers-how-come

best

compose now looks like this

version: '2.1'

services:

  admin:
    restart: always
    image: chrisss404/powerdns:latest-admin
    depends_on:
      - admin-db
      - authoritative
    environment:
      - ADMIN_PDNS_API_KEY=KEY
      - ADMIN_USER_PASSWORD=PASSWORD
    networks:
      - admin-db
      - authoritative
    ports:
      - "127.0.0.1:85:3031"
  admin-db:
    restart: always
    image: postgres:12.1-alpine
    environment:
      - POSTGRES_DB=pda
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_PASSWORD=pda
      - POSTGRES_USER=pda
    networks:
      - admin-db
    volumes:
        - ./admin-db:/var/lib/postgresql/data

  authoritative:
    restart: always
    image: chrisss404/powerdns:latest-authoritative
    depends_on:
      - authoritative-db
    environment:
      - AUTHORITATIVE_API=yes
      - AUTHORITATIVE_API_KEY=KEY
    ports:
      - 127.0.0.1:8081:8081
    networks:
      authoritative:
        ipv4_address: 172.31.118.118
      authoritative-db:

  authoritative-db:
    restart: always
    image: postgres:12.1-alpine
    environment:
      - POSTGRES_DB=pdns
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_PASSWORD=pdns
      - POSTGRES_USER=pdns
    networks:
      - authoritative-db
    volumes:
      - ./authoritative-db:/var/lib/postgresql/data

  dnsdist:
    restart: always
    image: chrisss404/powerdns:latest-dnsdist
    environment:
      - DNSDIST_API_KEY=KEY
      - DNSDIST_PLAIN=yes
      - DNSDIST_QUIET=no
    networks:
      recursor:
        ipv4_address: 172.31.117.118
    ports:
      - "53:53/tcp"
      - "53:53/udp"
  recursor:
    restart: always
    image: chrisss404/powerdns:latest-recursor
    environment:
      - RECURSOR_API_KEY=KEY
      - RECURSOR_FORWARD_ZONES=sys=172.31.118.118,fdsl.eu=172.31.118.118
      - RECURSOR_TRUST_ANCHORS=sys=54970 13 1 27efe1c1a790c3cbb43b947d6d6dfac62507097e,fdsl.eu=38731 13 1 32525245899859e208b00966b0242447ff6b00ee
      - RECURSOR_QUIET=yes
      - RECURSOR_DNSSEC=validate
    sysctls:
      - net.ipv6.route.max_size=16384
    networks:
      recursor:
        ipv4_address: 172.31.117.117
      authoritative:

networks:
  admin-db:
  authoritative:
    ipam:
      driver: default
      config:
        - subnet: "172.31.118.0/24"
  authoritative-db:
  recursor:
    ipam:
      driver: default
      config:
        - subnet: "172.31.117.0/24"

**Comment by chrisss404** [comment]
Hi firstdorsal,

you have to send the query directly to the authoritative server to get the AA flag. I assume you send your query to _dnsdist_?

You can see the difference in subsequent queries:

- Sending the query to the recursor returns these flags: qr rd ra ad
```
$ dig @172.31.117.117 start.staging.sys

; <<>> DiG 9.11.5-P4-5.1+deb10u1-Debian <<>> @172.31.117.117 start.staging.sys
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 24170
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;start.staging.sys.		IN	A

;; ANSWER SECTION:
start.staging.sys.	3593	IN	CNAME	debian1.local.staging.sys.
debian1.local.staging.sys. 3593	IN	A	10.0.0.132

;; Query time: 4 msec
;; SERVER: 172.31.117.117#53(172.31.117.117)
;; WHEN: Mon Jul 20 20:04:40 CEST 2020
;; MSG SIZE  rcvd: 90
```

- Sending the query to the authoritative server returns these flags: qr aa rd
```
$ dig @172.31.118.118 start.staging.sys

; <<>> DiG 9.11.5-P4-5.1+deb10u1-Debian <<>> @172.31.118.118 start.staging.sys
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 14112
;; flags: qr aa rd; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;start.staging.sys.		IN	A

;; ANSWER SECTION:
start.staging.sys.	3600	IN	CNAME	debian1.local.staging.sys.
debian1.local.staging.sys. 3600	IN	A	10.0.0.132

;; Query time: 0 msec
;; SERVER: 172.31.118.118#53(172.31.118.118)
;; WHEN: Mon Jul 20 20:04:37 CEST 2020
;; MSG SIZE  rcvd: 90
```

HTH & BR
Christian

**Comment by firstdorsal** [comment]
thank you.
i figured it out myself :)
