### ISSUE TITLE
powerdns-admin wont update to latest version

### ISSUE THREAD

**Issue by firstdorsal** [chrisss404/powerdns#5]
hi,
it seems like powerdns-admin wont update to the latest version.
the latest version should self host the fonts and not get them from google fonts anymore but it doesn't do this in your pdns-admin image.
any idea why?
cool project! thank you!
best
paul

**Comment by chrisss404** [comment]
Hi Paul,

unfortunately this is not yet supported, for more information see https://github.com/ngoduykhanh/PowerDNS-Admin/search?q=OFFLINE_MODE

Why do you think this should be available with the latest version?

BR
Christian

**Comment by firstdorsal** [comment]
i thought this would have been added as i saw the fonts:
https://github.com/ngoduykhanh/PowerDNS-Admin/tree/master/powerdnsadmin/static/assets/fonts
the fonts are not present in "chrisss404/powerdns:latest-admin"
best 
paul

**Comment by chrisss404** [comment]
Yeah sure, it is possible, but the image must be built with enabled OFFLINE MODE, which is currently not the case. Not sure what changes are required to make it work.

Do you have any use case that requires offline fonts?

**Comment by firstdorsal** [comment]
ohh okay, i didn't know that.
i'm not so comfortable using google fonts for privacy concerns that why i'm blocking them with uMatrix.
because of missing fallback fonts it falls back to using a serif font that looks interesting xD
